blog/urls.py
#!/usr/bin/env python
# coding:utf-8
"""
Name : urls
Author  : anne
Time    : 2019-12-25 11:56
Desc:
"""
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('posts/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    path('archives/<int:year>/<int:month>/',views.archive,name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('comments.urls'))

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.
class Category(models.Model):
    """
    文章分类
    """
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    文章标签
    """

    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

class Post(models.Model):
    """
    文章
        """

    def __str__(self):
        return self.title
    title = models.CharField('标题',max_length=70)
    body = models.TextField('正文')
    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField('创建时间',default=timezone.now())
    modified_time = models.DateTimeField('修改时间')
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField('摘要',max_length=200, blank=True)
    category = models.ForeignKey(Category,verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag,verbose_name='标签', blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是
    # django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和
    # Category 类似。
    author = models.ForeignKey(User,verbose_name='作者', on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0,editable=False)
    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']
    def save(self,*args,**kwargs):
        self.modified_time = timezone.now()
        md = markdown.Markdown(
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',

            ])
        self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})
    def increase_views(self):
        self.views +=1
        self.save(update_fields=['views'])

comments/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Comment(models.Model):
    name = models.CharField('名字',max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址',blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间',default=timezone.now)
    post = models.ForeignKey('blog.Post',verbose_name='文章',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}:{}'.format(self.name,self.text[:20])

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from .models import Post,Category,Tag
from django.views.generic import ListView,DetailView
import markdown
from pure_pagination  import PaginationMixin
import re


# Create your views here.
from django.http import HttpResponse


# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

def archive(request,year,month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month).order_by('-created_time')
    return render(request,'blog/index.html',context={'post_list':post_list})



# def tag(request,pk):
#     t = get_object_or_404(Tag,pk=pk)
#     post_list = Post.objects.filter(tags=t).order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

# def detail(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     #阅读量+1
#     post.increase_views()
#     md = markdown.Markdown(
#                          extensions=[
#                              'markdown.extensions.extra',
#                              'markdown.extensions.codehilite',
#                              TocExtension(slugify=slugify),
#
#                          ])
#     post.body = md.convert(post.body)
#     m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>',md.toc,re.S)
#     post.toc = m.group(1) if m is not None else ''
#     return render(request,'blog/detail.html',context={'post':post})



#-------------------------------------------------- 将试图函数改写成视图类
class IndexView(PaginationMixin,ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    #指定paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 10


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)

class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(category=t)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self,request,*args,**kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView,self).get(request,*args,**kwargs)

        #文章阅读量 +1
        #self.object的值就是被访问的文章
        self.object.increase_views()
        #视图必须返回一个HttpResponse对象
        return response
    def get_object(self, queryset=None):
        #复写get_object 方法的目的是因为需要对post的body值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''

        return post

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>Anne &amp; Fei</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body id="single">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }}  评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }}  阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">

                        <p>{{ post.body|safe }}</p>

                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    {% show_comment_form post %}
                    <div class="comment-list-panel">
                        {% show_comments post %}
                    </div>
{#                    <form action="#" method="post" class="comment-form">#}
{#                        <div class="row">#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_name">名字：</label>#}
{#                                <input type="text" id="id_name" name="name" required>#}
{#                            </div>#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_email">邮箱：</label>#}
{#                                <input type="email" id="id_email" name="email" required>#}
{#                            </div>#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_url">网址：</label>#}
{#                                <input type="text" id="id_url" name="url">#}
{#                            </div>#}
{#                            <div class="col-md-12">#}
{#                                <label for="id_comment">评论：</label>#}
{#                                <textarea name="comment" id="id_comment" required></textarea>#}
{#                                <button type="submit" class="comment-btn">发表</button>#}
{#                            </div>#}
{#                        </div>    <!-- row -->#}
{#                    </form>#}
{#                    <div class="comment-list-panel">#}
{#                        <h3>评论列表，共 <span>4</span> 条评论</h3>#}
{#                        <ul class="comment-list list-unstyled">#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">追梦人物</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>#}
{#                                <div class="text">#}
{#                                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">zmrenwu</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>#}
{#                                <div class="text">#}
{#                                    本能有可能会冲破格局，但格局有时候也会拘住本能。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">蝙蝠侠</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>#}
{#                                <div class="text">#}
{#                                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">长江七号</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>#}
{#                                <div class="text">#}
{#                                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死#}
{#                                </div>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
                </section>
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                    {% if post.toc %}
                        <div class="widget widget-content">
                            <h3 class="widget-title">文章目录</h3>
                            <div class="toc">
                                <ul>
                                    {{ post.toc|safe }}
                                </ul>
                            </div>

{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">教程特点</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">谁适合这个教程</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">在线预览</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">资源列表</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">获取帮助</a>#}
{#                        </li>#}
{#                    </ul>#}
                </div>
                    {% endif %}
                {% endblock toc %}
{#                <div class="widget widget-recent-posts">#}
{#                    <h3 class="widget-title">最新文章</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django 博客开发入门教程：前言</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">部署 Django 博客</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="widget widget-archives">#}
{#                    <h3 class="widget-title">归档</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">2017 年 5 月</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">2017 年 4 月</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">2017 年 3 月</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-category">#}
{#                    <h3 class="widget-title">分类</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-tag-cloud">#}
{#                    <h3 class="widget-title">标签云</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Java</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">笔记</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">文档</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">AngularJS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">CSS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">JavaScript</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Snippet</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">jQuery</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect from <a href="http://www.cssmoban.com/"
                                                                  target="_blank" title="模板之家">模板之家</a>
                    - Modified by <a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
{#            <li><a href="full-width.html">博客</a></li>#}
{#            <li><a href="about.html">关于</a></li>#}
{#            <li><a href="contact.html">联系</a></li>#}
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% for post in post_list %}
                    <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href={{ post.get_absolute_url }}>{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}  阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div class="no-post">暂时还没有发布出来的文章</div>
                {% endfor %}


{#                <!-- 简单分页效果#}
                {% if is_paginated %}
                <div class="pagination-simple">
                    <!--如果当前页还有上一页，显示上一页的按钮 -->
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}
                    <!--显示当前页的信息-->
                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                    <!--如果当前页还有下一页，显示下一页的按钮 -->
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                 {% endif %}
            {% endblock main %}
            </main>


<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
{#            <li><a href="full-width.html">博客</a></li>#}
{#            <li><a href="about.html">关于</a></li>#}
{#            <li><a href="contact.html">联系</a></li>#}
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>